/* eslint-disable */
export const DEFAULT_PLACEHOLDER = 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR4nGNasBQAAe4BSJC52v0AAAAASUVORK5CYII=';
export const DEFAULT_HEIGHT = 300;
export const DEFAULT_WIDTH = 300;
